### ISSUE TITLE
Updates needed after Bog Witch update

### ISSUE THREAD

**Issue by Shadowhmb** [The-Bees-Decree-Server/Distant-Dynasties#10]
your Bees Decrees mods for Valheim are currently broken due to Valheim Bog Witch update..... will there be a patch / update for those mods (Dustant Dynasties and Valkea)

**Comment by The-Bees-Decree-Server** [comment]
Code needs to be completely rewritten due to update. We are working on this currently but will take some time. Sorry for the inconvenience and thank you for understanding-

**Comment by Shadowhmb** [comment]
ty so very much for the reply... i was starting to think it had been
abandoned.  Your mods are awesome and I really appreciate all the work you
do

**Comment by The-Bees-Decree-Server** [comment]
fixed with v3.0.0 jvl

**Comment by Shadowhmb** [comment]
still broken..... try to create Bjork and it freezes during creation... you
can still move but thats it...... could another mod be interfering with it?
